### ISSUE TITLE
Rust Analyzer Crashes when editing variable identifier

### ISSUE THREAD

**Issue by achimcc** [rust-analyzer/rust-analyzer-wasm#11]
Hello,

I think this is a great Demo and at a first glimpse it seems to be stable and usable. However, I realized that Rust Analyzer crashes as soon as you edit one of the variable identifiers(`i32`). Seems to be resistant to other edits, though.

I started to use a WASM version of Rust Analyzer for another project and I'm running into the same error there. Do you have any idea why this bug occurs and what could be done about it?

I created a video of it:

https://user-images.githubusercontent.com/16603991/170993788-beae62e6-905c-4a79-a9c4-7bcb1ca07636.mp4

**Comment by bjorn3** [comment]
It seems to use 100% cpu for a while and after that hovering works again. I'm not quite sure what the issue is, but I would guess it is specific to the wasm version. I haven't seen any problems like this on the native version for projects of this size. It can occasionally be slow for much larger projects, but there there it automatically cancels requests like hover requests if necessary to preserve responsiveness. I don't think cancelation works on the wasm version.

![image](https://user-images.githubusercontent.com/17426603/170995716-c9e913c0-365d-4d07-8c49-f19bef0c87d9.png)

**Comment by achimcc** [comment]
Thanks for digging into this!

Yes, I agreee, that Rust Analyzer becomes responsive again after quite a while. I've the WASM version of Rust Analyzer inegrated into this Playground: https://ink-playground.substrate.io/ Here the `CrateGraph` / `Change` dependencies are considerably larger and when I edit e.g. a `bool` identifier for the first time, Rust Analyzer stops being responsive for minutes, but finally resumes to work and is only blocked for ~1-2s on the next edit of a `bool` identifier. I'd still like to improve this situation, if possible...

**Comment by achimcc** [comment]
It happened a few times to me, that Rust Analyzer threw a `max_overflow_depth_reached` error.

From my understanding it seems that Rust Analyzer continues to determine the type of the modified identifier (like bool -> bol), which it can't find. This seems to happen in the hir_ty crate by utilizing the chalk-recursive trait? Is there any modification that I could try which make Rust Analyzer giving up earlier on this attempt to recursively determine the type? 

What I already tried without success is to midify the  `CHALK_OVERFLOW_DEPTH` and `CHALK_SOLVER_MAX_SIZE` constants.

**Comment by achimcc** [comment]
I think I found the reason, why Rust Analyzer slows down. I created a PR #12 which describes and fixes the issue!
